# Generated by Django 3.0.6 on 2020-05-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("link", models.URLField()),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("amount_of_upvotes", models.PositiveIntegerField(default=0)),
                ("author_name", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("author_name", models.CharField(max_length=60)),
                ("content", models.CharField(max_length=120)),
                ("creation_date", models.DateField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.Post",
                    ),
                ),
            ],
        ),
    ]
